version: '3.8'

services:
  app:
    build:
      context: .
    container_name: "app"
    tty: true
    ports:
      - 3000:3000
    volumes:
      - .:/app
    environment:
      - WATCHPACK_POLLING=true
